INSERT INTO [DMSPOP].[dbo].[HUFS_MEDICINE]
           ([MedicineID]
           ,[MedicineName]
           ,[Description]
           ,[CreatedDate]
           ,[CreatedBy]
           ,[LastUpdatedDate]
           ,[LastUpdatedBy]
           ,[Status]
           ,[KhuyenMai]
           ,[GiaDNMua]
           ,[GiaDNMuaVAT]
           ,[GiaThucMua]
           ,[GiaKMMua]
           ,[GiaDNBan]
           ,[GiaDNBanVAT]
           ,[GiaThucBan]
           ,[MaKM]
           ,[BaoHiem]
           ,[MaChinhSachGia]
           ,[DienGiai]
           ,[STTTheoDMTCuaBYT]
           ,[TenThanhPhanThuoc]
           ,[HamLuong]
           ,[SoDKHoacGPKD]
           ,[DangBaoCheDuongUong]
           ,[NhaSanXuat]
           ,[QuocGia]
           ,[DonViTinh]
           ,[HoatDong]
           ,[CachUong]
           ,[Flag]
           ,[MaThuocYTe])
     SELECT 'ME0000000008' AS [MedicineID]
      ,[MedicineName]
      ,[Description]
      ,[CreatedDate]
      ,[CreatedBy]
      ,[LastUpdatedDate]
      ,[LastUpdatedBy]
      ,[Status]
      ,[KhuyenMai]
      ,[GiaDNMua]
      ,[GiaDNMuaVAT]
      ,[GiaThucMua]
      ,[GiaKMMua]
      ,[GiaDNBan]
      ,[GiaDNBanVAT]
      ,[GiaThucBan]
      ,[MaKM]
      ,[BaoHiem]
      ,[MaChinhSachGia]
      ,[DienGiai]
      ,[STTTheoDMTCuaBYT]
      ,[TenThanhPhanThuoc]
      ,[HamLuong]
      ,[SoDKHoacGPKD]
      ,[DangBaoCheDuongUong]
      ,[NhaSanXuat]
      ,[QuocGia]
      ,[DonViTinh]
      ,[HoatDong]
      ,[CachUong]
      ,[Flag]
      ,'ME0000000002' AS [MaThuocYTe]

  FROM [HUFS_MEDICINE]
  WHERE [MedicineID] = 'ME0000000002'


