USE [HTCC]
GO
/****** Object:  Table [dbo].[AssessmentDetails]    Script Date: 03/11/2015 20:37:15 ******/
DROP TABLE [dbo].[AssessmentDetails]
GO
/****** Object:  Table [dbo].[Assessments]    Script Date: 03/11/2015 20:37:15 ******/
DROP TABLE [dbo].[Assessments]
GO
/****** Object:  Table [dbo].[Calendars]    Script Date: 03/11/2015 20:37:15 ******/
DROP TABLE [dbo].[Calendars]
GO
/****** Object:  Table [dbo].[CheckInOut]    Script Date: 03/11/2015 20:37:15 ******/
DROP TABLE [dbo].[CheckInOut]
GO
/****** Object:  Table [dbo].[CheckInOut_PRD]    Script Date: 03/11/2015 20:37:15 ******/
DROP TABLE [dbo].[CheckInOut_PRD]
GO
/****** Object:  Table [dbo].[Credentials]    Script Date: 03/11/2015 20:37:15 ******/
DROP TABLE [dbo].[Credentials]
GO
/****** Object:  Table [dbo].[Departments]    Script Date: 03/11/2015 20:37:15 ******/
DROP TABLE [dbo].[Departments]
GO
/****** Object:  Table [dbo].[eLeaveForm]    Script Date: 03/11/2015 20:37:15 ******/
DROP TABLE [dbo].[eLeaveForm]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 03/11/2015 20:37:15 ******/
DROP TABLE [dbo].[Employees]
GO
/****** Object:  Table [dbo].[eTripForm]    Script Date: 03/11/2015 20:37:15 ******/
DROP TABLE [dbo].[eTripForm]
GO
/****** Object:  Table [dbo].[FPT_ENV_ACTIVATION_SCHEDULE]    Script Date: 03/11/2015 20:37:15 ******/
ALTER TABLE [dbo].[FPT_ENV_ACTIVATION_SCHEDULE] DROP CONSTRAINT [DF__FPT_ENV_A__ACTIV__77BFCB91]
GO
DROP TABLE [dbo].[FPT_ENV_ACTIVATION_SCHEDULE]
GO
/****** Object:  Table [dbo].[FPT_ENV_ACTUAL_PAYMENT]    Script Date: 03/11/2015 20:37:16 ******/
ALTER TABLE [dbo].[FPT_ENV_ACTUAL_PAYMENT] DROP CONSTRAINT [DF__FPT_ENV_A__Actua__0FBE76C2]
GO
ALTER TABLE [dbo].[FPT_ENV_ACTUAL_PAYMENT] DROP CONSTRAINT [DF__FPT_ENV_A__NoOfR__10B29AFB]
GO
ALTER TABLE [dbo].[FPT_ENV_ACTUAL_PAYMENT] DROP CONSTRAINT [DF__FPT_ENV_A__Order__11A6BF34]
GO
ALTER TABLE [dbo].[FPT_ENV_ACTUAL_PAYMENT] DROP CONSTRAINT [DF__FPT_ENV_A__Creat__129AE36D]
GO
ALTER TABLE [dbo].[FPT_ENV_ACTUAL_PAYMENT] DROP CONSTRAINT [DF__FPT_ENV_A__Updat__138F07A6]
GO
ALTER TABLE [dbo].[FPT_ENV_ACTUAL_PAYMENT] DROP CONSTRAINT [DF__FPT_ENV_A__Creat__14832BDF]
GO
ALTER TABLE [dbo].[FPT_ENV_ACTUAL_PAYMENT] DROP CONSTRAINT [DF__FPT_ENV_A__Updat__15775018]
GO
DROP TABLE [dbo].[FPT_ENV_ACTUAL_PAYMENT]
GO
/****** Object:  Table [dbo].[FPT_ENV_AUDIT_FINAL]    Script Date: 03/11/2015 20:37:16 ******/
DROP TABLE [dbo].[FPT_ENV_AUDIT_FINAL]
GO
/****** Object:  Table [dbo].[FPT_ENV_AUDIT_PLAN]    Script Date: 03/11/2015 20:37:16 ******/
DROP TABLE [dbo].[FPT_ENV_AUDIT_PLAN]
GO
/****** Object:  Table [dbo].[FPT_ENV_AUDIT_RESULT]    Script Date: 03/11/2015 20:37:16 ******/
ALTER TABLE [dbo].[FPT_ENV_AUDIT_RESULT] DROP CONSTRAINT [DF_FPT_ENV_AUDIT_RESULT_CREATEDATE]
GO
ALTER TABLE [dbo].[FPT_ENV_AUDIT_RESULT] DROP CONSTRAINT [DF_FPT_ENV_AUDIT_RESULT_STATUS]
GO
DROP TABLE [dbo].[FPT_ENV_AUDIT_RESULT]
GO
/****** Object:  Table [dbo].[FPT_ENV_AUDIT_RESULT_DETAIL]    Script Date: 03/11/2015 20:37:16 ******/
ALTER TABLE [dbo].[FPT_ENV_AUDIT_RESULT_DETAIL] DROP CONSTRAINT [DF__FPT_ENV_A__RESUL__1853BCC3]
GO
DROP TABLE [dbo].[FPT_ENV_AUDIT_RESULT_DETAIL]
GO
/****** Object:  Table [dbo].[FPT_ENV_AUDIT_RESULT_INFORMATION]    Script Date: 03/11/2015 20:37:16 ******/
ALTER TABLE [dbo].[FPT_ENV_AUDIT_RESULT_INFORMATION] DROP CONSTRAINT [DF__FPT_ENV_A__PS_CO__7D78A4E7]
GO
ALTER TABLE [dbo].[FPT_ENV_AUDIT_RESULT_INFORMATION] DROP CONSTRAINT [DF__FPT_ENV_A__OSA_C__7E6CC920]
GO
ALTER TABLE [dbo].[FPT_ENV_AUDIT_RESULT_INFORMATION] DROP CONSTRAINT [DF__FPT_ENV_A__NPD_C__7F60ED59]
GO
ALTER TABLE [dbo].[FPT_ENV_AUDIT_RESULT_INFORMATION] DROP CONSTRAINT [DF__FPT_ENV_A__SOS_C__00551192]
GO
ALTER TABLE [dbo].[FPT_ENV_AUDIT_RESULT_INFORMATION] DROP CONSTRAINT [DF__FPT_ENV_A__PRO_C__014935CB]
GO
ALTER TABLE [dbo].[FPT_ENV_AUDIT_RESULT_INFORMATION] DROP CONSTRAINT [DF__FPT_ENV_A__CTA_C__023D5A04]
GO
ALTER TABLE [dbo].[FPT_ENV_AUDIT_RESULT_INFORMATION] DROP CONSTRAINT [DF__FPT_ENV_A__SOF_C__03317E3D]
GO
ALTER TABLE [dbo].[FPT_ENV_AUDIT_RESULT_INFORMATION] DROP CONSTRAINT [DF__FPT_ENV_A__SHELF__0425A276]
GO
DROP TABLE [dbo].[FPT_ENV_AUDIT_RESULT_INFORMATION]
GO
/****** Object:  Table [dbo].[FPT_ENV_AUDIT_RESULT_MAPPING]    Script Date: 03/11/2015 20:37:16 ******/
DROP TABLE [dbo].[FPT_ENV_AUDIT_RESULT_MAPPING]
GO
/****** Object:  Table [dbo].[FPT_ENV_BASIC_DISPLAY_SET]    Script Date: 03/11/2015 20:37:16 ******/
DROP TABLE [dbo].[FPT_ENV_BASIC_DISPLAY_SET]
GO
/****** Object:  Table [dbo].[FPT_ENV_BASIC_EXTRA_DISPLAY_SET]    Script Date: 03/11/2015 20:37:16 ******/
DROP TABLE [dbo].[FPT_ENV_BASIC_EXTRA_DISPLAY_SET]
GO
/****** Object:  Table [dbo].[FPT_ENV_BASICDISPLAYSET_EXTRADISPLAYSET]    Script Date: 03/11/2015 20:37:16 ******/
DROP TABLE [dbo].[FPT_ENV_BASICDISPLAYSET_EXTRADISPLAYSET]
GO
/****** Object:  Table [dbo].[FPT_ENV_BLACKLIST]    Script Date: 03/11/2015 20:37:16 ******/
ALTER TABLE [dbo].[FPT_ENV_BLACKLIST] DROP CONSTRAINT [DF__FPT_ENV_B__Progr__2920B817]
GO
ALTER TABLE [dbo].[FPT_ENV_BLACKLIST] DROP CONSTRAINT [DF__FPT_ENV_B__ShipT__2A14DC50]
GO
ALTER TABLE [dbo].[FPT_ENV_BLACKLIST] DROP CONSTRAINT [DF__FPT_ENV_B__Store__2B090089]
GO
ALTER TABLE [dbo].[FPT_ENV_BLACKLIST] DROP CONSTRAINT [DF__FPT_ENV_B__Descr__2BFD24C2]
GO
ALTER TABLE [dbo].[FPT_ENV_BLACKLIST] DROP CONSTRAINT [DF__FPT_ENV_B__Creat__2CF148FB]
GO
ALTER TABLE [dbo].[FPT_ENV_BLACKLIST] DROP CONSTRAINT [DF__FPT_ENV_B__Updat__2DE56D34]
GO
ALTER TABLE [dbo].[FPT_ENV_BLACKLIST] DROP CONSTRAINT [DF__FPT_ENV_B__Creat__2ED9916D]
GO
ALTER TABLE [dbo].[FPT_ENV_BLACKLIST] DROP CONSTRAINT [DF__FPT_ENV_B__Updat__2FCDB5A6]
GO
DROP TABLE [dbo].[FPT_ENV_BLACKLIST]
GO
/****** Object:  Table [dbo].[FPT_ENV_BLENDED]    Script Date: 03/11/2015 20:37:16 ******/
ALTER TABLE [dbo].[FPT_ENV_BLENDED] DROP CONSTRAINT [DF__FPT_ENV_BLEN__PC__1DE57479]
GO
ALTER TABLE [dbo].[FPT_ENV_BLENDED] DROP CONSTRAINT [DF__FPT_ENV_BL__LPPC__1ED998B2]
GO
ALTER TABLE [dbo].[FPT_ENV_BLENDED] DROP CONSTRAINT [DF__FPT_ENV_BLEN__PS__1FCDBCEB]
GO
ALTER TABLE [dbo].[FPT_ENV_BLENDED] DROP CONSTRAINT [DF__FPT_ENV_BLE__OSA__20C1E124]
GO
ALTER TABLE [dbo].[FPT_ENV_BLENDED] DROP CONSTRAINT [DF__FPT_ENV_BLE__NPD__21B6055D]
GO
ALTER TABLE [dbo].[FPT_ENV_BLENDED] DROP CONSTRAINT [DF__FPT_ENV_B__SHELF__22AA2996]
GO
ALTER TABLE [dbo].[FPT_ENV_BLENDED] DROP CONSTRAINT [DF__FPT_ENV_B__PROMO__239E4DCF]
GO
ALTER TABLE [dbo].[FPT_ENV_BLENDED] DROP CONSTRAINT [DF__FPT_ENV_BLE__VPP__24927208]
GO
ALTER TABLE [dbo].[FPT_ENV_BLENDED] DROP CONSTRAINT [DF__FPT_ENV_B__TO_VA__25869641]
GO
DROP TABLE [dbo].[FPT_ENV_BLENDED]
GO
/****** Object:  Table [dbo].[FPT_ENV_CATEGORY]    Script Date: 03/11/2015 20:37:16 ******/
DROP TABLE [dbo].[FPT_ENV_CATEGORY]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHANNEL]    Script Date: 03/11/2015 20:37:16 ******/
DROP TABLE [dbo].[FPT_ENV_CHANNEL]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_CTA]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_CTA]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_CTA_DETAIL]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_CTA_DETAIL]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_KPI_APPLY]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_KPI_APPLY]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_NPD]    Script Date: 03/11/2015 20:37:17 ******/
ALTER TABLE [dbo].[FPT_ENV_CHECKLIST_NPD] DROP CONSTRAINT [DF__FPT_ENV_C__LAUNC__100EB873]
GO
ALTER TABLE [dbo].[FPT_ENV_CHECKLIST_NPD] DROP CONSTRAINT [DF__FPT_ENV_C__FROM___1102DCAC]
GO
ALTER TABLE [dbo].[FPT_ENV_CHECKLIST_NPD] DROP CONSTRAINT [DF__FPT_ENV_C__TO_DA__11F700E5]
GO
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_NPD]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_OSA]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_OSA]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_POSM]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_POSM]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_PROMOTION_COMPLIANCE]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_PROMOTION_COMPLIANCE]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_PROMOTION_COMPLIANCE_DETAIL]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_PROMOTION_COMPLIANCE_DETAIL]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_SCOPE_AREA]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_SCOPE_AREA]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_SCOPE_PSTYPE]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_SCOPE_PSTYPE]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_SHELF_STANDARD]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_SHELF_STANDARD]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_SOF]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_SOF]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_SOG]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_SOG]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_SOS]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_SOS]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_SSD]    Script Date: 03/11/2015 20:37:17 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_SSD]
GO
/****** Object:  Table [dbo].[FPT_ENV_CHECKLIST_STD_PRICE]    Script Date: 03/11/2015 20:37:18 ******/
DROP TABLE [dbo].[FPT_ENV_CHECKLIST_STD_PRICE]
GO
/****** Object:  Table [dbo].[FPT_ENV_COMPETITOR]    Script Date: 03/11/2015 20:37:18 ******/
ALTER TABLE [dbo].[FPT_ENV_COMPETITOR] DROP CONSTRAINT [DF_FPT_ENV_COMPETITOR_ACTIVE]
GO
DROP TABLE [dbo].[FPT_ENV_COMPETITOR]
GO
/****** Object:  Table [dbo].[FPT_ENV_CUSTOMER_TYPE]    Script Date: 03/11/2015 20:37:18 ******/
ALTER TABLE [dbo].[FPT_ENV_CUSTOMER_TYPE] DROP CONSTRAINT [DF_UKPI_CUSTOMER_TYPE_SUBTYPE]
GO
DROP TABLE [dbo].[FPT_ENV_CUSTOMER_TYPE]
GO
/****** Object:  Table [dbo].[FPT_ENV_DISPLAY_SET]    Script Date: 03/11/2015 20:37:18 ******/
ALTER TABLE [dbo].[FPT_ENV_DISPLAY_SET] DROP CONSTRAINT [DF__FPT_ENV_D__Iconi__24F7F41C]
GO
ALTER TABLE [dbo].[FPT_ENV_DISPLAY_SET] DROP CONSTRAINT [DF__FPT_ENV_D__Extra__25EC1855]
GO
ALTER TABLE [dbo].[FPT_ENV_DISPLAY_SET] DROP CONSTRAINT [DF__FPT_ENV_D__Activ__26E03C8E]
GO
ALTER TABLE [dbo].[FPT_ENV_DISPLAY_SET] DROP CONSTRAINT [DF__FPT_ENV_D__TOLim__27D460C7]
GO
ALTER TABLE [dbo].[FPT_ENV_DISPLAY_SET] DROP CONSTRAINT [DF__FPT_ENV_D__Incen__28C88500]
GO
ALTER TABLE [dbo].[FPT_ENV_DISPLAY_SET] DROP CONSTRAINT [DF__FPT_ENV_D__Displ__29BCA939]
GO
DROP TABLE [dbo].[FPT_ENV_DISPLAY_SET]
GO
/****** Object:  Table [dbo].[FPT_ENV_DISPLAY_SET_CATEGORIES]    Script Date: 03/11/2015 20:37:18 ******/
ALTER TABLE [dbo].[FPT_ENV_DISPLAY_SET_CATEGORIES] DROP CONSTRAINT [DF__FPT_ENV_D__Incen__1F00BA52]
GO
DROP TABLE [dbo].[FPT_ENV_DISPLAY_SET_CATEGORIES]
GO
/****** Object:  Table [dbo].[FPT_ENV_DISPLAY_SET_SHOP_FORMAT]    Script Date: 03/11/2015 20:37:18 ******/
DROP TABLE [dbo].[FPT_ENV_DISPLAY_SET_SHOP_FORMAT]
GO
/****** Object:  Table [dbo].[FPT_ENV_DISTRIBUTOR_EX_INFO]    Script Date: 03/11/2015 20:37:18 ******/
DROP TABLE [dbo].[FPT_ENV_DISTRIBUTOR_EX_INFO]
GO
/****** Object:  Table [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY]    Script Date: 03/11/2015 20:37:18 ******/
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__CUST___4CA06362]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__CUST___4D94879B]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__SHIP___4E88ABD4]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__SHIP___4F7CD00D]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__CUSTO__5070F446]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__CUSTO__5165187F]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__CUSTO__52593CB8]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__CUSTO__534D60F1]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__KEY_C__5441852A]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__KEY_C__5535A963]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__CHANN__5629CD9C]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__CHANN__571DF1D5]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__SUB_C__5812160E]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__SUB_C__59063A47]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__REGIO__59FA5E80]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__REGIO__5AEE82B9]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__PROVI__5BE2A6F2]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__PROVI__5CD6CB2B]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__SUB_P__5DCAEF64]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__SUB_P__5EBF139D]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__STRAT__5FB337D6]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__STATU__60A75C0F]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__WAREH__619B8048]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__WAREH__628FA481]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__SALES__6383C8BA]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__KEY_A__6477ECF3]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__CHANN__656C112C]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__CHANN__66603565]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__ABACU__6754599E]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__POP_S__68487DD7]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_DIS__DMS__693CA210]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__PPO_T__6A30C649]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__SUP_N__6B24EA82]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__SUP_M__6C190EBB]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__SUP_E__6D0D32F4]
GO
ALTER TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY] DROP CONSTRAINT [DF__FPT_ENV_D__ISNEW__6E01572D]
GO
DROP TABLE [dbo].[FPT_ENV_DISTRIBUTOR_HIERARCHY]
GO
/****** Object:  Table [dbo].[FPT_ENV_EXTRA_DISPLAY_SET]    Script Date: 03/11/2015 20:37:18 ******/
DROP TABLE [dbo].[FPT_ENV_EXTRA_DISPLAY_SET]
GO
/****** Object:  Table [dbo].[FPT_ENV_FILE_PROCESSING_LOG_DETAIL]    Script Date: 03/11/2015 20:37:18 ******/
DROP TABLE [dbo].[FPT_ENV_FILE_PROCESSING_LOG_DETAIL]
GO
/****** Object:  Table [dbo].[FPT_ENV_FILE_PROCESSING_LOG_HEADER]    Script Date: 03/11/2015 20:37:18 ******/
ALTER TABLE [dbo].[FPT_ENV_FILE_PROCESSING_LOG_HEADER] DROP CONSTRAINT [DF__FPT_ENV_F__Total__25ADB7E1]
GO
ALTER TABLE [dbo].[FPT_ENV_FILE_PROCESSING_LOG_HEADER] DROP CONSTRAINT [DF__FPT_ENV_F__Succe__26A1DC1A]
GO
DROP TABLE [dbo].[FPT_ENV_FILE_PROCESSING_LOG_HEADER]
GO
/****** Object:  Table [dbo].[FPT_ENV_FINAL_AUDIT_RESULT]    Script Date: 03/11/2015 20:37:18 ******/
ALTER TABLE [dbo].[FPT_ENV_FINAL_AUDIT_RESULT] DROP CONSTRAINT [DF__FPT_ENV_F__Audit__297E48C5]
GO
ALTER TABLE [dbo].[FPT_ENV_FINAL_AUDIT_RESULT] DROP CONSTRAINT [DF__FPT_ENV_F__IsSen__2A726CFE]
GO
ALTER TABLE [dbo].[FPT_ENV_FINAL_AUDIT_RESULT] DROP CONSTRAINT [DF__FPT_ENV_F__Appro__2B669137]
GO
ALTER TABLE [dbo].[FPT_ENV_FINAL_AUDIT_RESULT] DROP CONSTRAINT [DF__FPT_ENV_F__Comme__2C5AB570]
GO
ALTER TABLE [dbo].[FPT_ENV_FINAL_AUDIT_RESULT] DROP CONSTRAINT [DF__FPT_ENV_F__NoOfR__51B8B956]
GO
DROP TABLE [dbo].[FPT_ENV_FINAL_AUDIT_RESULT]
GO
/****** Object:  Table [dbo].[FPT_ENV_GP_GT_SALES_FORCE]    Script Date: 03/11/2015 20:37:18 ******/
DROP TABLE [dbo].[FPT_ENV_GP_GT_SALES_FORCE]
GO
/****** Object:  Table [dbo].[FPT_ENV_HOTSPOT]    Script Date: 03/11/2015 20:37:18 ******/
DROP TABLE [dbo].[FPT_ENV_HOTSPOT]
GO
/****** Object:  Table [dbo].[FPT_ENV_INSTALLATION_SCHEDULE]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_INSTALLATION_SCHEDULE] DROP CONSTRAINT [DF__FPT_ENV_I__INSTA__76969D2E]
GO
DROP TABLE [dbo].[FPT_ENV_INSTALLATION_SCHEDULE]
GO
/****** Object:  Table [dbo].[FPT_ENV_KEY_ACCOUNT]    Script Date: 03/11/2015 20:37:19 ******/
DROP TABLE [dbo].[FPT_ENV_KEY_ACCOUNT]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_CTA]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_KPI_CTA] DROP CONSTRAINT [DF__FPT_ENV_K__EXPOR__41543BA8]
GO
DROP TABLE [dbo].[FPT_ENV_KPI_CTA]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_NPD]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_KPI_NPD] DROP CONSTRAINT [DF_UKPI_KPI_NPD_EXPORTED]
GO
DROP TABLE [dbo].[FPT_ENV_KPI_NPD]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_OSA]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_KPI_OSA] DROP CONSTRAINT [DF__FPT_ENV_K__PROMO__6C2FB402]
GO
ALTER TABLE [dbo].[FPT_ENV_KPI_OSA] DROP CONSTRAINT [DF__FPT_ENV_K__PEAK___6D23D83B]
GO
ALTER TABLE [dbo].[FPT_ENV_KPI_OSA] DROP CONSTRAINT [DF__FPT_ENV_K__EXPOR__6E17FC74]
GO
DROP TABLE [dbo].[FPT_ENV_KPI_OSA]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_POSM]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_KPI_POSM] DROP CONSTRAINT [DF_UKPI_KPI_POSM_EXPORTED]
GO
DROP TABLE [dbo].[FPT_ENV_KPI_POSM]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_PROMOTION_COMPLIANCE]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_KPI_PROMOTION_COMPLIANCE] DROP CONSTRAINT [DF_UKPI_KPI_PROMOTION_COMPLIANCE_EXPORTED]
GO
DROP TABLE [dbo].[FPT_ENV_KPI_PROMOTION_COMPLIANCE]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_SOF]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_KPI_SOF] DROP CONSTRAINT [DF_UKPI_KPI_SOF_EXPORTED]
GO
DROP TABLE [dbo].[FPT_ENV_KPI_SOF]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_SOG]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_KPI_SOG] DROP CONSTRAINT [DF_UKPI_KPI_SOG_EXPORTED]
GO
DROP TABLE [dbo].[FPT_ENV_KPI_SOG]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_SOS]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_KPI_SOS] DROP CONSTRAINT [DF__FPT_ENV_K__EXPOR__2F358B6D]
GO
DROP TABLE [dbo].[FPT_ENV_KPI_SOS]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_SSD]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_KPI_SSD] DROP CONSTRAINT [DF_UKPI_KPI_SSD_EXPORTED]
GO
DROP TABLE [dbo].[FPT_ENV_KPI_SSD]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_SSGT]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_KPI_SSGT] DROP CONSTRAINT [DF_UKPI_KPI_SSGT_EXPORTED]
GO
DROP TABLE [dbo].[FPT_ENV_KPI_SSGT]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_SSMT]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_KPI_SSMT] DROP CONSTRAINT [DF_UKPI_KPI_SSMT_EXPORTED]
GO
DROP TABLE [dbo].[FPT_ENV_KPI_SSMT]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_STD_PRICE]    Script Date: 03/11/2015 20:37:19 ******/
ALTER TABLE [dbo].[FPT_ENV_KPI_STD_PRICE] DROP CONSTRAINT [DF_UKPI_KPI_STD_PRICE_EXPORTED]
GO
DROP TABLE [dbo].[FPT_ENV_KPI_STD_PRICE]
GO
/****** Object:  Table [dbo].[FPT_ENV_KPI_TYPE]    Script Date: 03/11/2015 20:37:19 ******/
DROP TABLE [dbo].[FPT_ENV_KPI_TYPE]
GO
/****** Object:  Table [dbo].[FPT_ENV_MAPPING_BASEPACK_VN]    Script Date: 03/11/2015 20:37:20 ******/
DROP TABLE [dbo].[FPT_ENV_MAPPING_BASEPACK_VN]
GO
/****** Object:  Table [dbo].[FPT_ENV_MAPPING_PRODUCT_VN]    Script Date: 03/11/2015 20:37:20 ******/
DROP TABLE [dbo].[FPT_ENV_MAPPING_PRODUCT_VN]
GO
/****** Object:  Table [dbo].[FPT_ENV_MAPPING_SECTOR_VN]    Script Date: 03/11/2015 20:37:20 ******/
DROP TABLE [dbo].[FPT_ENV_MAPPING_SECTOR_VN]
GO
/****** Object:  Table [dbo].[FPT_ENV_MAPPING_TEMP_VN]    Script Date: 03/11/2015 20:37:20 ******/
DROP TABLE [dbo].[FPT_ENV_MAPPING_TEMP_VN]
GO
/****** Object:  Table [dbo].[FPT_ENV_MARKETING_PROGRAM]    Script Date: 03/11/2015 20:37:20 ******/
ALTER TABLE [dbo].[FPT_ENV_MARKETING_PROGRAM] DROP CONSTRAINT [DF__FPT_ENV_M__MaxRe__53E7ED2F]
GO
ALTER TABLE [dbo].[FPT_ENV_MARKETING_PROGRAM] DROP CONSTRAINT [DF__FPT_ENV_M__MaxRe__54DC1168]
GO
ALTER TABLE [dbo].[FPT_ENV_MARKETING_PROGRAM] DROP CONSTRAINT [DF__FPT_ENV_M__MaxBa__55D035A1]
GO
ALTER TABLE [dbo].[FPT_ENV_MARKETING_PROGRAM] DROP CONSTRAINT [DF__FPT_ENV_M__MaxEx__56C459DA]
GO
ALTER TABLE [dbo].[FPT_ENV_MARKETING_PROGRAM] DROP CONSTRAINT [DF__FPT_ENV_M__IsSen__57B87E13]
GO
DROP TABLE [dbo].[FPT_ENV_MARKETING_PROGRAM]
GO
/****** Object:  Table [dbo].[FPT_ENV_MARKETING_PROGRAM_TYPE]    Script Date: 03/11/2015 20:37:20 ******/
DROP TABLE [dbo].[FPT_ENV_MARKETING_PROGRAM_TYPE]
GO
/****** Object:  Table [dbo].[FPT_ENV_MTChecklistNPDRawData]    Script Date: 03/11/2015 20:37:20 ******/
ALTER TABLE [dbo].[FPT_ENV_MTChecklistNPDRawData] DROP CONSTRAINT [DF__FPT_ENV_M__METRO__71C59635]
GO
ALTER TABLE [dbo].[FPT_ENV_MTChecklistNPDRawData] DROP CONSTRAINT [DF__FPT_ENV_M__BIG_C__72B9BA6E]
GO
ALTER TABLE [dbo].[FPT_ENV_MTChecklistNPDRawData] DROP CONSTRAINT [DF__FPT_ENV_M__GIANT__73ADDEA7]
GO
ALTER TABLE [dbo].[FPT_ENV_MTChecklistNPDRawData] DROP CONSTRAINT [DF__FPT_ENV_M__CITIM__74A202E0]
GO
ALTER TABLE [dbo].[FPT_ENV_MTChecklistNPDRawData] DROP CONSTRAINT [DF__FPT_ENV_M__SAIGO__75962719]
GO
ALTER TABLE [dbo].[FPT_ENV_MTChecklistNPDRawData] DROP CONSTRAINT [DF__FPT_ENV_M__LOTTE__768A4B52]
GO
ALTER TABLE [dbo].[FPT_ENV_MTChecklistNPDRawData] DROP CONSTRAINT [DF__FPT_ENV_M__MAXIM__777E6F8B]
GO
ALTER TABLE [dbo].[FPT_ENV_MTChecklistNPDRawData] DROP CONSTRAINT [DF__FPT_ENV_M__VINAT__787293C4]
GO
ALTER TABLE [dbo].[FPT_ENV_MTChecklistNPDRawData] DROP CONSTRAINT [DF__FPT_ENV_M__MT IN__7966B7FD]
GO
ALTER TABLE [dbo].[FPT_ENV_MTChecklistNPDRawData] DROP CONSTRAINT [DF__FPT_ENV_M__MT IN__7A5ADC36]
GO
DROP TABLE [dbo].[FPT_ENV_MTChecklistNPDRawData]
GO
/****** Object:  Table [dbo].[FPT_ENV_OUTLET_TYPE]    Script Date: 03/11/2015 20:37:20 ******/
DROP TABLE [dbo].[FPT_ENV_OUTLET_TYPE]
GO
/****** Object:  Table [dbo].[FPT_ENV_OUTLET_TYPE_DIVISION]    Script Date: 03/11/2015 20:37:20 ******/
DROP TABLE [dbo].[FPT_ENV_OUTLET_TYPE_DIVISION]
GO
/****** Object:  Table [dbo].[FPT_ENV_OUTLET_TYPE_SUB_DIVISION]    Script Date: 03/11/2015 20:37:20 ******/
DROP TABLE [dbo].[FPT_ENV_OUTLET_TYPE_SUB_DIVISION]
GO
/****** Object:  Table [dbo].[FPT_ENV_PARAMETERS]    Script Date: 03/11/2015 20:37:20 ******/
DROP TABLE [dbo].[FPT_ENV_PARAMETERS]
GO
/****** Object:  Table [dbo].[FPT_ENV_PRODUCT]    Script Date: 03/11/2015 20:37:20 ******/
ALTER TABLE [dbo].[FPT_ENV_PRODUCT] DROP CONSTRAINT [DF__FPT_ENV_P__STATU__76384129]
GO
DROP TABLE [dbo].[FPT_ENV_PRODUCT]
GO
/****** Object:  Table [dbo].[FPT_ENV_PRODUCT_temp]    Script Date: 03/11/2015 20:37:20 ******/
DROP TABLE [dbo].[FPT_ENV_PRODUCT_temp]
GO
/****** Object:  Table [dbo].[FPT_ENV_PRODUCT_temppp]    Script Date: 03/11/2015 20:37:20 ******/
DROP TABLE [dbo].[FPT_ENV_PRODUCT_temppp]
GO
/****** Object:  Table [dbo].[FPT_ENV_PRODUCTHIERARCHY_DISPLAYSET]    Script Date: 03/11/2015 20:37:20 ******/
ALTER TABLE [dbo].[FPT_ENV_PRODUCTHIERARCHY_DISPLAYSET] DROP CONSTRAINT [DF__FPT_ENV_P__NUMBE__22751F6C]
GO
DROP TABLE [dbo].[FPT_ENV_PRODUCTHIERARCHY_DISPLAYSET]
GO
/****** Object:  Table [dbo].[FPT_ENV_PROMOTION_PRODUCT]    Script Date: 03/11/2015 20:37:21 ******/
DROP TABLE [dbo].[FPT_ENV_PROMOTION_PRODUCT]
GO
/****** Object:  Table [dbo].[FPT_ENV_PROMOTION_SCHEDULE]    Script Date: 03/11/2015 20:37:21 ******/
ALTER TABLE [dbo].[FPT_ENV_PROMOTION_SCHEDULE] DROP CONSTRAINT [DF__FPT_ENV_P__PROMO__2739D489]
GO
DROP TABLE [dbo].[FPT_ENV_PROMOTION_SCHEDULE]
GO
/****** Object:  Table [dbo].[FPT_ENV_PS_TYPE]    Script Date: 03/11/2015 20:37:21 ******/
DROP TABLE [dbo].[FPT_ENV_PS_TYPE]
GO
/****** Object:  Table [dbo].[FPT_ENV_REGISTERED_DISPLAY_STORES]    Script Date: 03/11/2015 20:37:21 ******/
ALTER TABLE [dbo].[FPT_ENV_REGISTERED_DISPLAY_STORES] DROP CONSTRAINT [DF__FPT_ENV_R__NoOfR__302B4654]
GO
ALTER TABLE [dbo].[FPT_ENV_REGISTERED_DISPLAY_STORES] DROP CONSTRAINT [DF__FPT_ENV_R__IsSen__311F6A8D]
GO
DROP TABLE [dbo].[FPT_ENV_REGISTERED_DISPLAY_STORES]
GO
/****** Object:  Table [dbo].[FPT_ENV_REGISTERED_STORE_LOG_DETAIL]    Script Date: 03/11/2015 20:37:21 ******/
DROP TABLE [dbo].[FPT_ENV_REGISTERED_STORE_LOG_DETAIL]
GO
/****** Object:  Table [dbo].[FPT_ENV_REGISTRATION_CAPACITY_EXCEPTION]    Script Date: 03/11/2015 20:37:21 ******/
ALTER TABLE [dbo].[FPT_ENV_REGISTRATION_CAPACITY_EXCEPTION] DROP CONSTRAINT [DF__FPT_ENV_R__Modif__35E41FAA]
GO
ALTER TABLE [dbo].[FPT_ENV_REGISTRATION_CAPACITY_EXCEPTION] DROP CONSTRAINT [DF__FPT_ENV_R__IsSen__36D843E3]
GO
DROP TABLE [dbo].[FPT_ENV_REGISTRATION_CAPACITY_EXCEPTION]
GO
/****** Object:  Table [dbo].[FPT_ENV_REJECTLIST]    Script Date: 03/11/2015 20:37:21 ******/
ALTER TABLE [dbo].[FPT_ENV_REJECTLIST] DROP CONSTRAINT [DF__FPT_ENV_R__Progr__208B7216]
GO
ALTER TABLE [dbo].[FPT_ENV_REJECTLIST] DROP CONSTRAINT [DF__FPT_ENV_R__ShipT__217F964F]
GO
ALTER TABLE [dbo].[FPT_ENV_REJECTLIST] DROP CONSTRAINT [DF__FPT_ENV_R__Store__2273BA88]
GO
ALTER TABLE [dbo].[FPT_ENV_REJECTLIST] DROP CONSTRAINT [DF__FPT_ENV_R__Descr__2367DEC1]
GO
ALTER TABLE [dbo].[FPT_ENV_REJECTLIST] DROP CONSTRAINT [DF__FPT_ENV_R__Creat__245C02FA]
GO
ALTER TABLE [dbo].[FPT_ENV_REJECTLIST] DROP CONSTRAINT [DF__FPT_ENV_R__Updat__25502733]
GO
ALTER TABLE [dbo].[FPT_ENV_REJECTLIST] DROP CONSTRAINT [DF__FPT_ENV_R__Creat__26444B6C]
GO
ALTER TABLE [dbo].[FPT_ENV_REJECTLIST] DROP CONSTRAINT [DF__FPT_ENV_R__Updat__27386FA5]
GO
DROP TABLE [dbo].[FPT_ENV_REJECTLIST]
GO
/****** Object:  Table [dbo].[FPT_ENV_SHIPTOCODE_EMAIL]    Script Date: 03/11/2015 20:37:21 ******/
DROP TABLE [dbo].[FPT_ENV_SHIPTOCODE_EMAIL]
GO
/****** Object:  Table [dbo].[FPT_ENV_SHOP_TYPE]    Script Date: 03/11/2015 20:37:21 ******/
DROP TABLE [dbo].[FPT_ENV_SHOP_TYPE]
GO
/****** Object:  Table [dbo].[FPT_ENV_SHOPFORMAT_BASICDISPLAYSET]    Script Date: 03/11/2015 20:37:21 ******/
DROP TABLE [dbo].[FPT_ENV_SHOPFORMAT_BASICDISPLAYSET]
GO
/****** Object:  Table [dbo].[FPT_ENV_STORE]    Script Date: 03/11/2015 20:37:21 ******/
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF_UKPI_STORE_TURNOVER]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__UKPI_STOR__CHANN__7ADF5CBA]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__CUSTO__339FAB6E]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__STORE__3493CFA7]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__STORE__3587F3E0]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__STORE__367C1819]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__SHOP___37703C52]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__MARKE__3864608B]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__STREE__395884C4]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__STREE__3A4CA8FD]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_ST__WARD__3B40CD36]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__CITY___3C34F16F]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__CITY___3D2915A8]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__SALES__3E1D39E1]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__SALES__3F115E1A]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__AREA___40058253]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__AREA___40F9A68C]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__TERRI__41EDCAC5]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__TERRI__42E1EEFE]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__ROUTE__43D61337]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__ROUTE__44CA3770]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__LATIT__45BE5BA9]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__LONGI__46B27FE2]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__STATU__47A6A41B]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__CREAT__489AC854]
GO
ALTER TABLE [dbo].[FPT_ENV_STORE] DROP CONSTRAINT [DF__FPT_ENV_S__LUPD___498EEC8D]
GO
DROP TABLE [dbo].[FPT_ENV_STORE]
GO
/****** Object:  Table [dbo].[FPT_ENV_STORE_temp]    Script Date: 03/11/2015 20:37:21 ******/
DROP TABLE [dbo].[FPT_ENV_STORE_temp]
GO
/****** Object:  Table [dbo].[FPT_ENV_STORE_tttt]    Script Date: 03/11/2015 20:37:21 ******/
DROP TABLE [dbo].[FPT_ENV_STORE_tttt]
GO
/****** Object:  Table [dbo].[FPT_ENV_SummaryMTForProm]    Script Date: 03/11/2015 20:37:21 ******/
ALTER TABLE [dbo].[FPT_ENV_SummaryMTForProm] DROP CONSTRAINT [DF__FPT_ENV_S__METRO__2EEB72AA]
GO
ALTER TABLE [dbo].[FPT_ENV_SummaryMTForProm] DROP CONSTRAINT [DF__FPT_ENV_S__BIG_C__2FDF96E3]
GO
ALTER TABLE [dbo].[FPT_ENV_SummaryMTForProm] DROP CONSTRAINT [DF__FPT_ENV_S__GIANT__30D3BB1C]
GO
ALTER TABLE [dbo].[FPT_ENV_SummaryMTForProm] DROP CONSTRAINT [DF__FPT_ENV_S__CITIM__31C7DF55]
GO
ALTER TABLE [dbo].[FPT_ENV_SummaryMTForProm] DROP CONSTRAINT [DF__FPT_ENV_S__SAIGO__32BC038E]
GO
ALTER TABLE [dbo].[FPT_ENV_SummaryMTForProm] DROP CONSTRAINT [DF__FPT_ENV_S__LOTTE__33B027C7]
GO
ALTER TABLE [dbo].[FPT_ENV_SummaryMTForProm] DROP CONSTRAINT [DF__FPT_ENV_S__MAXIM__34A44C00]
GO
ALTER TABLE [dbo].[FPT_ENV_SummaryMTForProm] DROP CONSTRAINT [DF__FPT_ENV_S__VINAT__35987039]
GO
ALTER TABLE [dbo].[FPT_ENV_SummaryMTForProm] DROP CONSTRAINT [DF__FPT_ENV_S__MT IN__368C9472]
GO
ALTER TABLE [dbo].[FPT_ENV_SummaryMTForProm] DROP CONSTRAINT [DF__FPT_ENV_S__MT IN__3780B8AB]
GO
DROP TABLE [dbo].[FPT_ENV_SummaryMTForProm]
GO
/****** Object:  Table [dbo].[FPT_ENV_TO_LIMIT_EXCEPTION]    Script Date: 03/11/2015 20:37:21 ******/
ALTER TABLE [dbo].[FPT_ENV_TO_LIMIT_EXCEPTION] DROP CONSTRAINT [DF__FPT_ENV_T__Modif__3D854172]
GO
ALTER TABLE [dbo].[FPT_ENV_TO_LIMIT_EXCEPTION] DROP CONSTRAINT [DF__FPT_ENV_T__IsSen__3E7965AB]
GO
DROP TABLE [dbo].[FPT_ENV_TO_LIMIT_EXCEPTION]
GO
/****** Object:  Table [dbo].[FPT_ENV_Todo_list]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[FPT_ENV_Todo_list]
GO
/****** Object:  Table [dbo].[FPT_ENV_TOWN]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[FPT_ENV_TOWN]
GO
/****** Object:  Table [dbo].[GP_DMS_CITY]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[GP_DMS_CITY]
GO
/****** Object:  Table [dbo].[GP_DMS_OUTLETHIERARCHY]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[GP_DMS_OUTLETHIERARCHY]
GO
/****** Object:  Table [dbo].[GP_DMS_OUTLETS]    Script Date: 03/11/2015 20:37:22 ******/
ALTER TABLE [dbo].[GP_DMS_OUTLETS] DROP CONSTRAINT [DF_GP_DMS_OUTLETS_UPDATE_STATUS]
GO
DROP TABLE [dbo].[GP_DMS_OUTLETS]
GO
/****** Object:  Table [dbo].[GP_DMS_PROVINCE]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[GP_DMS_PROVINCE]
GO
/****** Object:  Table [dbo].[GP_ENV_TRANSFER_LOG]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[GP_ENV_TRANSFER_LOG]
GO
/****** Object:  Table [dbo].[GP_GT_OUTLETS_TEMP]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[GP_GT_OUTLETS_TEMP]
GO
/****** Object:  Table [dbo].[KPIScore2014]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[KPIScore2014]
GO
/****** Object:  Table [dbo].[LeaveClass]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[LeaveClass]
GO
/****** Object:  Table [dbo].[LeaveClassNew]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[LeaveClassNew]
GO
/****** Object:  Table [dbo].[LeaveDay]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[LeaveDay]
GO
/****** Object:  Table [dbo].[Link]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[Link]
GO
/****** Object:  Table [dbo].[PhieuThuong]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[PhieuThuong]
GO
/****** Object:  Table [dbo].[Province]    Script Date: 03/11/2015 20:37:22 ******/
DROP TABLE [dbo].[Province]
GO