
INSERT INTO [HTCC].[dbo].[tb_ev_log]
           ([RID]
           ,[REFID]
           ,[REFID_TYP]
           ,[LOGDEVID]
           ,[LOGDEVDTLID]
           ,[LOGDEVTYPEID]
           ,[LOGDEVDESCRP]
           ,[LOGDEVADESCRP]
           ,[LOGDEVTYPEDESC]
           ,[EVNT_ADDR]
           ,[REC_DAT]
           ,[EVNT_DAT]
           ,[EVNT_DESCRP]
           ,[DESCRP]
           ,[LOCATION]
           ,[LOOP_DESCRP]
           ,[PANEL_DESCRP]
           ,[BADGENO]
           ,[CARDNO]
           ,[LNAME]
           ,[FNAME]
           ,[MI]
           ,[STAT_COD]
           ,[ISSUE_LEV]
           ,[COMP_ID]
           ,[COMP_NAME]
           ,[THREAT_LEV]
           ,[INXIT]
           ,[LAST_ACC]
           ,[EXPIRE_DAT]
           ,[ISSUE_DAT]
           ,[PINCODE]
           ,[VDAT]
           ,[MSG]
           ,[PRI]
           ,[ALTYP_ID]
           ,[SHUNT]
           ,[TRACE]
           ,[WRKST]
           ,[UID]
           ,[TSTAMP]
           ,[DEVICE_GUID]
           ,[EVENT_GUID])
    

SELECT TOP 1000 [RID]
      ,[REFID]
      ,[REFID_TYP]
      ,[LOGDEVID]
      ,[LOGDEVDTLID]
      ,[LOGDEVTYPEID]
      ,[LOGDEVDESCRP]
      ,[LOGDEVADESCRP]
      ,[LOGDEVTYPEDESC]
      ,[EVNT_ADDR]
      ,[REC_DAT]
      ,[EVNT_DAT]
      ,[EVNT_DESCRP]
      ,[DESCRP]
      ,[LOCATION]
      ,[LOOP_DESCRP]
      ,[PANEL_DESCRP]
      ,[BADGENO]
      ,[CARDNO]
      ,[LNAME]
      ,[FNAME]
      ,[MI]
      ,[STAT_COD]
      ,[ISSUE_LEV]
      ,[COMP_ID]
      ,[COMP_NAME]
      ,[THREAT_LEV]
      ,[INXIT]
      ,[LAST_ACC]
      ,[EXPIRE_DAT]
      ,[ISSUE_DAT]
      ,[PINCODE]
      ,[VDAT]
      ,[MSG]
      ,[PRI]
      ,[ALTYP_ID]
      ,[SHUNT]
      ,[TRACE]
      ,[WRKST]
      ,[UID]
      ,[TSTAMP]
      ,[DEVICE_GUID]
      ,[EVENT_GUID]
  FROM [PWNT].[dbo].[EV_LOG]
ORDER BY REC_DAT DESC


